import { VendorBase } from './VendorBase';
import { VendorBookarestaurant } from './VendorBookarestaurant';
import { VendorBookatable } from './VendorBookatable';
import { VendorChope } from './VendorChope';
import { VendorCovermanager } from './VendorCovermanager';
import { VendorDineout } from './VendorDineout';
import { VendorDinesuperb } from './VendorDinesuperb';
import { VendorEat2Eat } from './VendorEat2Eat';
import { VendorEztable } from './VendorEztable';
import { VendorFunNow } from './VendorFunNow';
import { VendorIkyu } from './VendorIkyu';
import { VendorInlineApp } from './VendorInlineApp';
import { VendorLafourchette } from './VendorLafourchette';
import { VendorOmakase } from './VendorOmakase';
import { VendorOpentable } from './VendorOpentable';
import { VendorPocketConcierge } from './VendorPocketConcierge';
import { VendorQuandoo } from './VendorQuandoo';
import { VendorResdiary } from './VendorResdiary';
import { VendorResengo } from './VendorResengo';
import { VendorRestaurantes } from './VendorRestaurantes';
import { VendorResy } from './VendorResy';
import { VendorSevenrooms } from './VendorSevenrooms';
import { VendorTabelog } from './VendorTabelog';
import { VendorTock } from './VendorTock';
import { VendorToreta } from './VendorToreta';
import { VendorYelp } from './VendorYelp';
import { VendorZenchef } from './VendorZenchef';

type tplotOptions = {
    [key: string]: VendorBase
};

export const VendorMap: tplotOptions = {
    opentable: new VendorOpentable(),
    resy: new VendorResy(),
    tock: new VendorTock(),
    bookarestaurant: new VendorBookarestaurant(),
    bookatable: new VendorBookatable(),
    dinesuperb: new VendorDinesuperb(),
    resdiary: new VendorResdiary(),
    sevenrooms: new VendorSevenrooms(),
    yelp: new VendorYelp(),
    // tablecheck: new VendorTablecheck(),
    "pocket-concierge": new VendorPocketConcierge(),
    toreta: new VendorToreta(),
    omakase: new VendorOmakase(),
    ikyu: new VendorIkyu(),
    chope: new VendorChope(),
    funnow: new VendorFunNow(),
    dineout: new VendorDineout(),
    tabelog: new VendorTabelog(),
    eat2eat: new VendorEat2Eat(),
    quandoo: new VendorQuandoo(),
    inline: new VendorInlineApp(),
    eztable: new VendorEztable(),
    lafourchette: new VendorLafourchette(),
    zenchef: new VendorZenchef(),
    covermanager: new VendorCovermanager(),
    restaurantes: new VendorRestaurantes(),
    "resengo.com": new VendorResengo(),
}
/*

const VendorKeywordMap =
{
    "opentable.": "opentable",
    "bookatable.": "bookatable",
    "resdiary.": "resdiary",
    "dinesuperb.": "dinesuperb",
    "resy.com": "resy",
    "exploretock.": "tock",
    "tocktix.": "tock",
    "bookarestaurant.": "bookarestaurant",
    "sevenrooms.": "sevenrooms",
    "tablecheck.": "tablecheck",
    "pocket-concierge": "pocket-concierge",
    "toreta.": "toreta",
    // yelp, // too many sites have yelp link
    "omakase.in": "omakase",
    "ikyu.": "ikyu",
    "chope.co": "chope",
    "funnow.": "funnow",
    "dineout.": "dineout",
    "tabelog.": "tabelog",
    "eat2eat.": "eat2eat",
    "quandoo.": "quandoo",
    "eztable.": "eztable",
    "gnavi.": "gnavi",
    "gourmate.": "gourmate",
    "hotpepper.": "hotpepper",
    "hungryhub.": "hungryhub",
    "ikky.": "ikky",
    "inline.app": "inline",
    "seatris.": "seatris",
    "shangri-la.": "shangri-la",
    "tableall.": "tableall",
    "travelclick.": "travelclick",
    "webjapan.": "webjapan",
    "toptable.": "opentable",
    "kernowonline.": "kernowonline",
    "waiteraid.": "waiteraid",
    "mytable.info": "mytable.info",
    "lafourchette.": "lafourchette",
    "reserveddining.": "reserveddining",
    "togo.uk.": "togo.uk",
    "restaurant-live": "restaurant-live",
    "liveres.": "liveres",
    "catchtable.": "catchtable",
    "hitosara": "hitosara",
    "optitable.": "optitable",
    "restaurants.sg": "restaurants.sg",
    "restaurantes.com": "restaurantes",
    "resebook.": "resebook",
    "tagme.": "tagme",
    "acuityscheduling": "acuityscheduling",
    "jtb.co": "jtb",
    "rguest.com": "rguest",
    "bokabord.": "bokabord",
    "diningcity.": "diningcity",
    "ebica.": "ebica",
    "jpneasy.": "jpneasy",
    "kyusanko.": "kyusanko",
    "ambatel.": "ambatel",
    "buzztable.": "buzztable",
    "capricebookings.": "capricebookings",
    "doublebluesq.": "doublebluesq",
    "giftrocker.": "giftrocker",
    "govoyagin.": "govoyagin",
    "jalan.net": "jalan",
    "lottehotel.": "lottehotel",
    "myconciergejapan.": "myconciergejapan",
    "naver.": "naver",
    "tastetrip.": "tastetrip",
    "poing.": "poing",
    "resmio.com": "resmio",
    "accesso.com": "accesso",
    "appointy.": "appointy",
    "asoview.": "asoview",
    "bepretty.cl": "bepretty.cl",
    "bookeo.": "bookeo",
    "bookingkit": "bookingkit",
    "booksy.": "booksy",
    "trycake.com": "trycake.com",
    "checkfront.": "checkfront",
    "chefsclub.": "chefsclub",
    "clickypass.": "clickypass",
    "designmynight.": "designmynight",
    "coursehorse.": "coursehorse",
    "covermanager.": "covermanager",
    "dineout.co.": "dineout.co.",
    "qsrautomations.": "qsrautomations",
    "eatapp.": "eatapp",
    "eazydiner.": "eazydiner",
    "eet.nu": "eet.nu",
    "envisionsalon": "envisionsalon",
    "etender.nl": "etender.nl",
    "eveve.com": "eveve.com",
    "fareharbor.": "fareharbor",
    "flexybeauty.": "flexybeauty",
    "formitable.": "formitable",
    "fullslate.": "fullslate",
    "genbook.com": "genbook.com",
    "gendo.com": "gendo.com",
    "getyourguide.": "getyourguide",
    "globalticket.": "globalticket",
    "goldstar.com": "goldstar.com",
    "gopanache.": "gopanache",
    "guestonline.": "guestonline",
    "gurunavi.com": "gurunavi.com",
    "hornblower": "hornblower",
    "hd.digital": "hd.digital",
    "hostmeapp": "hostmeapp",
    "hungrygowhere.": "hungrygowhere",
    "klook.com": "klook.com",
    "thefork": "thefork",
    // "leclick": "leclick",
    "libroreserve": "libroreserve",
    "massagebook": "massagebook",
    "meitre.": "meitre",
    "mindbodyonline": "mindbodyonline",
    "musement.": "musement",
    "mytime.com": "mytime.com",
    "opensalon.": "opensalon.",
    "peek.com": "peek.com",
    "pike13.com": "pike13.com",
    "regiondo.": "regiondo",
    "usereso.": "usereso",
    "restorando.": "restorando",
    "rezdy.com": "rezdy.com",
    "rosysalonsoftware": "rosysalonsoftware",
    "salonrunner.": "salonrunner",
    "seatninja.": "seatninja",
    "setmore.com": "setmore.com",
    "shore.com": "shore.com",
    "shortcuts.com": "shortcuts.com",
    "showpass.com": "showpass.com",
    "solocal.com": "solocal.com",
    "squareup": "squareup",
    "getsquire": "getsquire",
    "tablebooker": "tablebooker",
    "thestudiodirector": "thestudiodirector",
    "simplybook": "simplybook",
    "supersalon": "supersalon",
    "thepronails.com": "thepronails.com",
    "thryv.com": "thryv.com",
    "timetrade": "timetrade",
    "tiqets.": "tiqets",
    "tomesto.": "tomesto",
    "treatwell.": "treatwell",
    "trinks.": "trinks",
    "tripshock.": "tripshock",
    "vaniday.": "vaniday",
    "vcita.": "vcita",
    "viator.com": "viator.com",
    "vimbly.": "vimbly",
    "waitlist.me": "waitlist.me",
    "wellnessliving.": "wellnessliving",
    "getwisely.": "getwisely",
    "xola.": "xola",
    "yclients.": "yclients",
    "yocale.": "yocale",
    "zenchef.": "zenchef",
    "zooty.": "zooty",
    "afisha.": "afisha",
    "appbarber.": "appbarber",
    "bewe.io": "bewe.io",
    "bookinghound.": "bookinghound",
    "coconutsoftware.": "coconutsoftware",
    "coubic.": "coubic",
    "dineplan.": "dineplan",
    "easytablebooking.": "easytablebooking",
    "eatigo.": "eatigo",
    "ebisol.": "ebisol",
    "epark.jp": "epark.jp",
    "e-table.gr": "e-table",
    "eventbrite.": "eventbrite",
    "byinti.": "byinti",
    "isango.": "isango",
    "jrni.": "jrni",
    "jtech.": "jtech",
    "kkday.": "kkday",
    "leciseau.": "leciseau",
    "liftopia.": "liftopia",
    "mangeznotez.": "mangeznotez",
    "mesa247.": "mesa247",
    "midioresto.": "midioresto",
    "milanosoftware.": "milanosoftware",
    "mygon.": "mygon",
    "nerdmonster.": "nerdmonster",
    "palisis.": "palisis",
    "planity.": "planity",
    "precompro.": "precompro",
    "qraved.": "qraved",
    "radiusnetworks.": "radiusnetworks",
    "redeam.": "redeam",
    "resengo.com": "resengo.com",
    "reservandonos.": "reservandonos",
    "cross-feed.com": "cross-feed.com",
    "retty.me": "retty.me",
    "riservi.": "riservi",
    "salaovip.": "salaovip",
    "salonbizsoftware": "salonbizsoftware",
    "salonized": "salonized",
    "schedulicity": "schedulicity",
    "seatgeek": "seatgeek",
    "seetickets": "seetickets",
    "showclix": "showclix",
    "simpleerb": "simpleerb",
    "tablecheck": "tablecheck",
    "ticketmaster": "ticketmaster",
    "uala.it": "uala.it",
    "versum.": "versum",
    "zaui.com": "zaui.com",
    "wavy.co": "wavy.co",
    "gastronavi.": "gastronavi", // .de
    "prenota-web": "prenota-web", // .it
    "atavolo.": "atavolo",
    "littlerestaurant.": "littlerestaurant", // .de
    "okura.": "okura", // .de
    "cloud-reservations": "cloud-reservations", // .de
    "vincitables": "vincitables", // .de
    "wereserve": "wereserve",
    "etender.": "etender",
    "dinnerbooking.": "dinnerbooking",
    "peninsula.": "peninsula",
    "verticalbooking.": "verticalbooking",
    "tableonline.": "tableonline",
    "foratable.": "foratable",
    "tabledb.": "tabledb",
    "prmrsv.": "prmrsv",
    "loco.yahoo": "locoyahoo",
    "netfood.cloud": "netfood",
    "lenclume.co": "lenclume.co",
    "i-host.": "i-host",
    "blastnessbooking.": "blastnessbooking",
    "nappkin.": "nappkin",
    "tablepath.com": "tablepath.com",
    "tablefever.be": "tablefever.be",
    "tablein.com": "tablein",
    "guestcentric": "guestcentric",
    //new
    "guestplan.": "guestplan",
    "avenista.": "avenista",
    "aleno.me": "aleno",
    "verk.fo": "verk",
    "xtable.ch": "xtable",
    "seatme.": "seatme",
    "revoflow.works": "revoflow",
    "bookiopro.": "bookiopro",
}

var VendorTypes1: Array<string> = [];

VendorTypes1.push("yelp");
VendorTypes1 = VendorTypes1.concat(Object.values(VendorKeywordMap))


exports.VendorKeywordMap = VendorKeywordMap;

export const VendorTypes = VendorTypes1.sort();
*/

export const getVendor = (type: string): VendorBase => {
    return VendorMap[type];
}