name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/217254739278/locations/global/workloadIdentityPools/my-pool1/providers/my-provider'
        service_account: 'postgraphile-svc-user@yumyum-v2.iam.gserviceaccount.com'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    #- name: Build & Publish
      #run: |
        #gcloud config set project ${{ secrets.GCP_PROJECT }}
        #gcloud config set run/region us-central1

    #- uses: fastai/workflows/ssh@master
      #with:
        #ssh_key: ${{ secrets.SSH_KEY }}
        #key_file: id_ecdsa
    #- name: Setup tmate session
      #uses: mxschmitt/action-tmate@master

    - name: move module over something 
      run: cd graphql ; mv ../src/yummodule . ; cd ..
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy graph --source graphql --region us-central1 --allow-unauthenticated --memory 512M
