name: run-scrape

on:
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - id: 'create-file'
      run: echo 'hello' > ${{steps.date.outputs.date }}.txt

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: ${{ steps.date.outputs.date }}.txt
        destination: 'yumyum-v2_cloudbuild'