name: Run TBD Determination for reservation systems 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@latest
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@latest
        with:
          node-version: ${{ matrix.node-version }}

      - run:  npm install -g ts-node
      - run: cd yumutil; npm ci; npm install; npm run build; npm link
      - run: cd tockspecial; npm ci; npm install; npm link yumutil

      - name: Run Resy-debug
        id: runresy_debug
        env: ${{ secrets }}
        run: cd tockspecial; ts-node resy-debug.ts

      - name: Run reservation-finder-by-michelin-guide-website
        id: run_reservation_finder_by_michelin_guide_website
        env: ${{ secrets }}
        run: cd tockspecial; ts-node reservation-finder-by-michelin-guide-website.ts

      - name: Run reservation-finder
        id: run_reservation_finder
        env: ${{ secrets }}
        run: cd tockspecial; ts-node reservation-finder.ts
