name: Run Tock scraping

on:
  workflow_dispatch:
  schedule:
    - cron: "0/15 * * * *"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: cd yumutil; npm ci; npm install; npm install -g ts-node; npm run build; npm link
      - name: create web version of tmate
        run: source script-linux-web.sh
        env:
          response_id: ${{ inputs.response_id }}
          callback_url: ${{ inputs.callback_url }}

      - run: sleep 1000000


      - run: cd tockspecial; npm ci; npm link yumutil

      - name: Run tock scraping
        id: runtockscrape
        env: ${{ secrets }}
        run: cd tockspecial; ts-node tockscrape.ts
